image:
  repository: localhost:32000/go-lxd-vm-dashboard
  tag: "latest"
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80
  targetPort: 8080 # This MUST match your Go app logs

lxd:
  address: "https://10.0.0.162:8443"

# Point Helm to the secret you already created manually
existingSecretName: "openbao-creds"

ingress:
  enabled: true
  className: "public"
  host: "lxd-dashboard.local"
