apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: VAULT_SKIP_VERIFY
              value: "true"  # This fixes the 'unknown authority' error
            - name: LXD_ADDR
              value: {{ .Values.lxd.address | quote }}
          # Pulls VAULT_ADDR, VAULT_ROLE_ID, and VAULT_SECRET_ID from the secret
          envFrom:
            - secretRef:
                name: {{ .Values.existingSecretName }}
